events {}

http {

    client_max_body_size 500M;

    upstream backend_servers {

        server backend1:8000;
        server backend2:8000;
        server backend3:8000;

    }

    upstream frontend {

        server frontend:80;

    }

    server {

        listen 80;

        location / {

            proxy_pass http://frontend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }

        location /api/ {

            rewrite ^/api/(.*)$ /$1 break;

            proxy_pass http://backend_servers;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }

    }

}